services:
  api-alunos:
    build: .
    ports:
      - 8081:8081
    container_name: api-alunos
    environment:
      POSTGRES_URL: jdbc:postgresql://postgres:5432/user_db
    depends_on:
      - postgres
      - pgadmin
  postgres:
    image: postgres:16.1-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: post123
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: m@adminpgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80